/*
# Mandals - Telangana

Inserting mandals for Telangana districts.
*/

INSERT INTO mandals (district_id, name, type)
SELECT d.id, m.name, m.type FROM districts d, (VALUES
-- Medchal Malkajgiri Mandal
('Medchal Malkajgiri', 'Medchal', 'mandal'),
('Medchal Malkajgiri', 'Keesara', 'mandal'),
('Medchal Malkajgiri', 'Shamirpet', 'mandal'),
('Medchal Malkajgiri', 'Ghatkesar', 'mandal'),
('Medchal Malkajgiri', 'Malkajgiri', 'mandal'),
('Medchal Malkajgiri', 'Secunderabad', 'mandal'),
('Medchal Malkajgiri', 'Alwal', 'mandal'),
('Medchal Malkajgiri', 'Kapra', 'mandal'),
('Medchal Malkajgiri', 'Uppal', 'mandal'),
('Medchal Malkajgiri', 'Balapur', 'mandal'),
('Medchal Malkajgiri', 'Saroornagar', 'mandal'),
('Medchal Malkajgiri', 'Hayathnagar', 'mandal'),
-- Rangareddy Mandals
('Rangareddy', 'Chevella', 'mandal'),
('Rangareddy', 'Shadnagar', 'mandal'),
('Rangareddy', 'Maheswaram', 'mandal'),
('Rangareddy', 'Ibrahimpatnam', 'mandal'),
('Rangareddy', 'Yalal', 'mandal'),
('Rangareddy', 'Pargi', 'mandal'),
('Rangareddy', 'Farooqnagar', 'mandal'),
('Rangareddy', 'Kandukur', 'mandal'),
('Rangareddy', 'Manchal', 'mandal'),
('Rangareddy', 'Moinabad', 'mandal'),
('Rangareddy', 'Rajendranagar', 'mandal'),
('Rangareddy', 'Serilingampally', 'mandal'),
('Rangareddy', 'Shamshabad', 'mandal'),
('Rangareddy', 'Kesampet', 'mandal'),
('Rangareddy', 'Marpally', 'mandal'),
('Rangareddy', 'Nawabpet', 'mandal'),
('Rangareddy', 'Kulkacherla', 'mandal'),
('Rangareddy', 'Tandur', 'mandal'),
-- Hyderabad Mandals
('Hyderabad', 'Khairatabad', 'mandal'),
('Hyderabad', 'Asifnagar', 'mandal'),
('Hyderabad', 'Nampally', 'mandal'),
('Hyderabad', 'Saidabad', 'mandal'),
('Hyderabad', 'Charminar', 'mandal'),
('Hyderabad', 'Hussainialam', 'mandal'),
('Hyderabad', 'Bahadurpura', 'mandal'),
('Hyderabad', 'Golconda', 'mandal'),
('Hyderabad', 'Maredpally', 'mandal'),
('Hyderabad', 'Tirumalagiri', 'mandal'),
('Hyderabad', 'Shaikpet', 'mandal'),
('Hyderabad', 'Bandlaguda', 'mandal'),
('Hyderabad', 'Chandrayangutta', 'mandal'),
('Hyderabad', 'Kanchanbagh', 'mandal'),
('Hyderabad', 'Rajendra Nagar', 'mandal'),
-- Nalgonda Mandals
('Nalgonda', 'Nalgonda', 'mandal'),
('Nalgonda', 'Miryalaguda', 'mandal'),
('Nalgonda', 'Devarakonda', 'mandal'),
('Nalgonda', 'Kodad', 'mandal'),
('Nalgonda', 'Huzurnagar', 'mandal'),
('Nalgonda', 'Suryapet', 'mandal'),
('Nalgonda', 'Narketpally', 'mandal'),
('Nalgonda', 'Chityala', 'mandal'),
('Nalgonda', 'Nampally', 'mandal'),
('Nalgonda', 'Munugode', 'mandal'),
('Nalgonda', 'Marriguda', 'mandal'),
('Nalgonda', 'Chandur', 'mandal'),
('Nalgonda', 'Kattangoor', 'mandal'),
('Nalgonda', 'Mothe', 'mandal'),
('Nalgonda', 'Thripuraram', 'mandal'),
('Nalgonda', 'Nidamanuru', 'mandal'),
('Nalgonda', 'Gurrampode', 'mandal'),
('Nalgonda', 'Peddavoora', 'mandal'),
('Nalgonda', 'Pedda Adiserla Pally', 'mandal'),
('Nalgonda', 'Anumula', 'mandal'),
('Nalgonda', 'Vemulapally', 'mandal'),
('Nalgonda', 'Penpahad', 'mandal'),
('Nalgonda', 'Jajireddygudem', 'mandal'),
('Nalgonda', 'Atmakur', 'mandal'),
('Nalgonda', 'Gundala', 'mandal'),
('Nalgonda', 'Mella Cheruvu', 'mandal'),
('Nalgonda', 'Garide Pally', 'mandal'),
('Nalgonda', 'Kethepally', 'mandal'),
('Nalgonda', 'Chilkur', 'mandal'),
('Nalgonda', 'Munagala', 'mandal'),
-- Karimnagar Mandals
('Karimnagar', 'Karimnagar', 'mandal'),
('Karimnagar', 'Huzurabad', 'mandal'),
('Karimnagar', 'Jagtial', 'mandal'),
('Karimnagar', 'Korutla', 'mandal'),
('Karimnagar', 'Metpally', 'mandal'),
('Karimnagar', 'Peddapalli', 'mandal'),
('Karimnagar', 'Manthani', 'mandal'),
('Karimnagar', 'Ramagundam', 'mandal'),
('Karimnagar', 'Sircilla', 'mandal'),
('Karimnagar', 'Choppadandi', 'mandal'),
('Karimnagar', 'Gangadhara', 'mandal'),
('Karimnagar', 'Sulthanabad', 'mandal'),
('Karimnagar', 'Velgatoor', 'mandal'),
('Karimnagar', 'Mahadevpur', 'mandal'),
('Karimnagar', 'Malyal', 'mandal'),
('Karimnagar', 'Jammikunta', 'mandal'),
('Karimnagar', 'Veenavanka', 'mandal'),
('Karimnagar', 'Husnabad', 'mandal'),
('Karimnagar', 'Mutharam', 'mandal'),
('Karimnagar', 'Odela', 'mandal'),
('Karimnagar', 'Kalwa Srirampur', 'mandal'),
('Karimnagar', 'Raikal', 'mandal'),
('Karimnagar', 'Mallial', 'mandal'),
('Karimnagar', 'Pegadapally', 'mandal'),
('Karimnagar', 'Kamanpur', 'mandal'),
('Karimnagar', 'Kothapally', 'mandal'),
('Karimnagar', 'Sarangaapur', 'mandal'),
('Karimnagar', 'Ibrahimpatnam', 'mandal'),
('Karimnagar', 'Keshtampet', 'mandal'),
('Karimnagar', 'Boenpally', 'mandal'),
-- Warangal Rural Mandals
('Warangal Rural', 'Nekkonda', 'mandal'),
('Warangal Rural', 'Geesukonda', 'mandal'),
('Warangal Rural', 'Atmakur', 'mandal'),
('Warangal Rural', 'Sangem', 'mandal'),
('Warangal Rural', 'Wardhanna Pet', 'mandal'),
('Warangal Rural', 'Parakala', 'mandal'),
('Warangal Rural', 'Duggondi', 'mandal'),
('Warangal Rural', 'Hasanparthy', 'mandal'),
('Warangal Rural', 'Chityala', 'mandal'),
('Warangal Rural', 'Zaffergadh', 'mandal'),
('Warangal Rural', 'Raiparthy', 'mandal'),
('Warangal Rural', 'Raghunathapalle', 'mandal'),
('Warangal Rural', 'Narsmpet', 'mandal'),
('Warangal Rural', 'Chravell', 'mandal'),
('Warangal Rural', 'Parkal', 'mandal'),
-- Warangal Urban Mandals
('Warangal Urban', 'Hanamkonda', 'mandal'),
('Warangal Urban', 'Warangal', 'mandal'),
('Warangal Urban', 'Kazipet', 'mandal'),
-- Mahabubnagar Mandals
('Mahabubnagar', 'Mahabubnagar', 'mandal'),
('Mahabubnagar', 'Gadwal', 'mandal'),
('Mahabubnagar', 'Wanaparthy', 'mandal'),
('Mahabubnagar', 'Narayanpet', 'mandal'),
('Mahabubnagar', 'Makthal', 'mandal'),
('Mahabubnagar', 'Dhanwada', 'mandal'),
('Mahabubnagar', 'Atmakur', 'mandal'),
('Mahabubnagar', 'Jadcherla', 'mandal'),
('Mahabubnagar', 'Kalwakurthy', 'mandal'),
('Mahabubnagar', 'Achampet', 'mandal'),
('Mahabubnagar', 'Kollapur', 'mandal'),
('Mahabubnagar', 'Pebbair', 'mandal'),
('Mahabubnagar', 'Veepangandla', 'mandal'),
('Mahabubnagar', 'Bijinepally', 'mandal'),
('Mahabubnagar', 'Pangal', 'mandal'),
('Mahabubnagar', 'Ghanpur', 'mandal'),
('Mahabubnagar', 'Devarakadra', 'mandal'),
('Mahabubnagar', 'Koilkonda', 'mandal'),
('Mahabubnagar', 'Moosapet', 'mandal'),
('Mahabubnagar', 'Balanagar', 'mandal'),
('Mahabubnagar', 'Midjil', 'mandal'),
('Mahabubnagar', 'Vangoor', 'mandal'),
('Mahabubnagar', 'Talakondapally', 'mandal'),
('Mahabubnagar', 'Nandigama', 'mandal'),
('Mahabubnagar', 'Thimmajipet', 'mandal'),
('Mahabubnagar', 'Addakal', 'mandal'),
('Mahabubnagar', 'Bhoothpur', 'mandal'),
('Mahabubnagar', 'Rajapur', 'mandal'),
('Mahabubnagar', 'Kodangal', 'mandal'),
('Mahabubnagar', 'Yalal', 'mandal'),
-- Khammam Mandals
('Khammam', 'Khammam', 'mandal'),
('Khammam', 'Kothagudem', 'mandal'),
('Khammam', 'Palwancha', 'mandal'),
('Khammam', 'Yellandu', 'mandal'),
('Khammam', 'Sathupally', 'mandal'),
('Khammam', 'Madhira', 'mandal'),
('Khammam', 'Wyra', 'mandal'),
('Khammam', 'Thallada', 'mandal'),
('Khammam', 'Kusumanchi', 'mandal'),
('Khammam', 'Vemsoor', 'mandal'),
('Khammam', 'Chintalapalem', 'mandal'),
('Khammam', 'Penubally', 'mandal'),
('Khammam', 'Aswaraopeta', 'mandal'),
('Khammam', 'Sujathanagar', 'mandal'),
('Khammam', 'Kukkunoor', 'mandal'),
('Khammam', 'Velepadu', 'mandal'),
('Khammam', 'Burgampahad', 'mandal'),
('Khammam', 'Chandrugonda', 'mandal'),
('Khammam', 'Gundala', 'mandal'),
('Khammam', 'Dammapeta', 'mandal'),
('Khammam', 'Cherla', 'mandal'),
('Khammam', 'Manugur', 'mandal'),
('Khammam', 'Bhadrachalam', 'mandal'),
('Khammam', 'Dummugudem', 'mandal'),
('Khammam', 'Vararamachandrapuram', 'mandal'),
('Khammam', 'Kunavaram', 'mandal'),
('Khammam', 'Allapally', 'mandal'),
('Khammam', 'Enkuru', 'mandal'),
('Khammam', 'Nelakondapally', 'mandal'),
('Khammam', 'Karepally', 'mandal')
) AS m(district, name, type)
WHERE d.name = m.district
ON CONFLICT DO NOTHING;
