/*
# India Districts - Part 2

Inserting districts for more states.
*/

INSERT INTO districts (state_id, name, code)
SELECT s.id, d.name, d.code FROM states s, (VALUES
-- Uttar Pradesh Districts (75)
('Uttar Pradesh', 'Agra', 'AG'),
('Uttar Pradesh', 'Aligarh', 'AL'),
('Uttar Pradesh', 'Ambedkar Nagar', 'AN'),
('Uttar Pradesh', 'Amethi', 'AM'),
('Uttar Pradesh', 'Amroha', 'AO'),
('Uttar Pradesh', 'Auraiya', 'AU'),
('Uttar Pradesh', 'Ayodhya', 'AY'),
('Uttar Pradesh', 'Azamgarh', 'AZ'),
('Uttar Pradesh', 'Baghpat', 'BT'),
('Uttar Pradesh', 'Bahraich', 'BH'),
('Uttar Pradesh', 'Ballia', 'BL'),
('Uttar Pradesh', 'Balrampur', 'BR'),
('Uttar Pradesh', 'Banda', 'BD'),
('Uttar Pradesh', 'Barabanki', 'BB'),
('Uttar Pradesh', 'Bareilly', 'BA'),
('Uttar Pradesh', 'Basti', 'BS'),
('Uttar Pradesh', 'Bhadohi', 'BH'),
('Uttar Pradesh', 'Bijnor', 'BI'),
('Uttar Pradesh', 'Budaun', 'BU'),
('Uttar Pradesh', 'Bulandshahr', 'BG'),
('Uttar Pradesh', 'Chandauli', 'CH'),
('Uttar Pradesh', 'Chitrakoot', 'CK'),
('Uttar Pradesh', 'Deoria', 'DE'),
('Uttar Pradesh', 'Etah', 'ET'),
('Uttar Pradesh', 'Etawah', 'EW'),
('Uttar Pradesh', 'Farrukhabad', 'FK'),
('Uttar Pradesh', 'Fatehpur', 'FP'),
('Uttar Pradesh', 'Firozabad', 'FZ'),
('Uttar Pradesh', 'Gautam Buddha Nagar', 'GB'),
('Uttar Pradesh', 'Ghaziabad', 'GZ'),
('Uttar Pradesh', 'Ghazipur', 'GP'),
('Uttar Pradesh', 'Gonda', 'GN'),
('Uttar Pradesh', 'Gorakhpur', 'GO'),
('Uttar Pradesh', 'Hamirpur', 'HM'),
('Uttar Pradesh', 'Hapur', 'HP'),
('Uttar Pradesh', 'Hardoi', 'HR'),
('Uttar Pradesh', 'Hathras', 'HA'),
('Uttar Pradesh', 'Jalaun', 'JL'),
('Uttar Pradesh', 'Jaunpur', 'JP'),
('Uttar Pradesh', 'Jhansi', 'JH'),
('Uttar Pradesh', 'Kannauj', 'KJ'),
('Uttar Pradesh', 'Kanpur Dehat', 'KD'),
('Uttar Pradesh', 'Kanpur Nagar', 'KN'),
('Uttar Pradesh', 'Kasganj', 'KG'),
('Uttar Pradesh', 'Kaushambi', 'KB'),
('Uttar Pradesh', 'Kushinagar', 'KU'),
('Uttar Pradesh', 'Lakhimpur Kheri', 'LK'),
('Uttar Pradesh', 'Lalitpur', 'LT'),
('Uttar Pradesh', 'Lucknow', 'LU'),
('Uttar Pradesh', 'Maharajganj', 'MJ'),
('Uttar Pradesh', 'Mahoba', 'MA'),
('Uttar Pradesh', 'Mainpuri', 'MI'),
('Uttar Pradesh', 'Mathura', 'MT'),
('Uttar Pradesh', 'Mau', 'MU'),
('Uttar Pradesh', 'Meerut', 'ME'),
('Uttar Pradesh', 'Mirzapur', 'MZ'),
('Uttar Pradesh', 'Moradabad', 'MO'),
('Uttar Pradesh', 'Muzaffarnagar', 'MG'),
('Uttar Pradesh', 'Pilibhit', 'PI'),
('Uttar Pradesh', 'Pratapgarh', 'PR'),
('Uttar Pradesh', 'Prayagraj', 'PY'),
('Uttar Pradesh', 'Rae Bareli', 'RB'),
('Uttar Pradesh', 'Rampur', 'RM'),
('Uttar Pradesh', 'Saharanpur', 'SA'),
('Uttar Pradesh', 'Sambhal', 'SB'),
('Uttar Pradesh', 'Sant Kabir Nagar', 'SK'),
('Uttar Pradesh', 'Shahjahanpur', 'SH'),
('Uttar Pradesh', 'Shamli', 'SM'),
('Uttar Pradesh', 'Shrawasti', 'SW'),
('Uttar Pradesh', 'Siddharthnagar', 'SN'),
('Uttar Pradesh', 'Sitapur', 'SI'),
('Uttar Pradesh', 'Sonbhadra', 'SO'),
('Uttar Pradesh', 'Sultanpur', 'SU'),
('Uttar Pradesh', 'Unnao', 'UU'),
('Uttar Pradesh', 'Varanasi', 'VR'),
-- Madhya Pradesh Districts (55)
('Madhya Pradesh', 'Agar Malwa', 'AM'),
('Madhya Pradesh', 'Alirajpur', 'AL'),
('Madhya Pradesh', 'Anuppur', 'AN'),
('Madhya Pradesh', 'Ashoknagar', 'AS'),
('Madhya Pradesh', 'Balaghat', 'BL'),
('Madhya Pradesh', 'Barwani', 'BW'),
('Madhya Pradesh', 'Betul', 'BT'),
('Madhya Pradesh', 'Bhind', 'BH'),
('Madhya Pradesh', 'Bhopal', 'BP'),
('Madhya Pradesh', 'Burhanpur', 'BU'),
('Madhya Pradesh', 'Chhatarpur', 'CH'),
('Madhya Pradesh', 'Chhindwara', 'CN'),
('Madhya Pradesh', 'Damoh', 'DA'),
('Madhya Pradesh', 'Datia', 'DT'),
('Madhya Pradesh', 'Dewas', 'DW'),
('Madhya Pradesh', 'Dhar', 'DH'),
('Madhya Pradesh', 'Dindori', 'DD'),
('Madhya Pradesh', 'Guna', 'GN'),
('Madhya Pradesh', 'Gwalior', 'GW'),
('Madhya Pradesh', 'Harda', 'HR'),
('Madhya Pradesh', 'Hoshangabad', 'HS'),
('Madhya Pradesh', 'Indore', 'IN'),
('Madhya Pradesh', 'Jabalpur', 'JB'),
('Madhya Pradesh', 'Jhabua', 'JH'),
('Madhya Pradesh', 'Katni', 'KT'),
('Madhya Pradesh', 'Khandwa', 'KH'),
('Madhya Pradesh', 'Khargone', 'KG'),
('Madhya Pradesh', 'Mandla', 'ML'),
('Madhya Pradesh', 'Mandsaur', 'MS'),
('Madhya Pradesh', 'Morena', 'MO'),
('Madhya Pradesh', 'Narsinghpur', 'NR'),
('Madhya Pradesh', 'Neemuch', 'NE'),
('Madhya Pradesh', 'Panna', 'PN'),
('Madhya Pradesh', 'Raisen', 'RA'),
('Madhya Pradesh', 'Rajgarh', 'RJ'),
('Madhya Pradesh', 'Ratlam', 'RT'),
('Madhya Pradesh', 'Rewa', 'RE'),
('Madhya Pradesh', 'Sagar', 'SG'),
('Madhya Pradesh', 'Satna', 'ST'),
('Madhya Pradesh', 'Sehore', 'SE'),
('Madhya Pradesh', 'Seoni', 'SN'),
('Madhya Pradesh', 'Shahdol', 'SH'),
('Madhya Pradesh', 'Shajapur', 'SJ'),
('Madhya Pradesh', 'Sheopur', 'SP'),
('Madhya Pradesh', 'Shivpuri', 'SV'),
('Madhya Pradesh', 'Sidhi', 'SI'),
('Madhya Pradesh', 'Singrauli', 'SG'),
('Madhya Pradesh', 'Tikamgarh', 'TK'),
('Madhya Pradesh', 'Ujjain', 'UJ'),
('Madhya Pradesh', 'Umaria', 'UM'),
('Madhya Pradesh', 'Vidisha', 'VI'),
-- Gujarat Districts (33)
('Gujarat', 'Ahmedabad', 'AH'),
('Gujarat', 'Amreli', 'AM'),
('Gujarat', 'Anand', 'AN'),
('Gujarat', 'Aravalli', 'AR'),
('Gujarat', 'Banaskantha', 'BA'),
('Gujarat', 'Bharuch', 'BH'),
('Gujarat', 'Bhavnagar', 'BV'),
('Gujarat', 'Botad', 'BO'),
('Gujarat', 'Chhota Udaipur', 'CU'),
('Gujarat', 'Dahod', 'DA'),
('Gujarat', 'Dang', 'DN'),
('Gujarat', 'Devbhumi Dwarka', 'DD'),
('Gujarat', 'Gandhinagar', 'GN'),
('Gujarat', 'Gir Somnath', 'GS'),
('Gujarat', 'Jamnagar', 'JA'),
('Gujarat', 'Junagadh', 'JU'),
('Gujarat', 'Kheda', 'KH'),
('Gujarat', 'Kutch', 'KU'),
('Gujarat', 'Mahisagar', 'MA'),
('Gujarat', 'Mehsana', 'ME'),
('Gujarat', 'Morbi', 'MO'),
('Gujarat', 'Narmada', 'NA'),
('Gujarat', 'Navsari', 'NV'),
('Gujarat', 'Panchmahal', 'PA'),
('Gujarat', 'Patan', 'PT'),
('Gujarat', 'Porbandar', 'PO'),
('Gujarat', 'Rajkot', 'RA'),
('Gujarat', 'Sabarkantha', 'SA'),
('Gujarat', 'Surat', 'SU'),
('Gujarat', 'Surendranagar', 'SN'),
('Gujarat', 'Tapi', 'TA'),
('Gujarat', 'Vadodara', 'VA'),
-- Rajasthan Districts (50)
('Rajasthan', 'Ajmer', 'AJ'),
('Rajasthan', 'Alwar', 'AL'),
('Rajasthan', 'Banswara', 'BA'),
('Rajasthan', 'Baran', 'BR'),
('Rajasthan', 'Barmer', 'BM'),
('Rajasthan', 'Bharatpur', 'BH'),
('Rajasthan', 'Bhilwara', 'BI'),
('Rajasthan', 'Bikaner', 'BK'),
('Rajasthan', 'Bundi', 'BU'),
('Rajasthan', 'Chittorgarh', 'CH'),
('Rajasthan', 'Churu', 'CR'),
('Rajasthan', 'Dausa', 'DA'),
('Rajasthan', 'Dholpur', 'DH'),
('Rajasthan', 'Dungarpur', 'DU'),
('Rajasthan', 'Hanumangarh', 'HA'),
('Rajasthan', 'Jaipur', 'JA'),
('Rajasthan', 'Jaisalmer', 'JS'),
('Rajasthan', 'Jalore', 'JL'),
('Rajasthan', 'Jhalawar', 'JH'),
('Rajasthan', 'Jhunjhunu', 'JJ'),
('Rajasthan', 'Jodhpur', 'JD'),
('Rajasthan', 'Karauli', 'KR'),
('Rajasthan', 'Kota', 'KO'),
('Rajasthan', 'Nagaur', 'NA'),
('Rajasthan', 'Pali', 'PA'),
('Rajasthan', 'Pratapgarh', 'PR'),
('Rajasthan', 'Rajsamand', 'RJ'),
('Rajasthan', 'Sawai Madhopur', 'SM'),
('Rajasthan', 'Sikar', 'SI'),
('Rajasthan', 'Sirohi', 'SR'),
('Rajasthan', 'Sri Ganganagar', 'SG'),
('Rajasthan', 'Tonk', 'TO'),
('Rajasthan', 'Udaipur', 'UD')
) AS d(state, name, code)
WHERE s.name = d.state
ON CONFLICT DO NOTHING;
