/*
# India Districts - Part 3

Inserting remaining states districts.
*/

INSERT INTO districts (state_id, name, code)
SELECT s.id, d.name, d.code FROM states s, (VALUES
-- West Bengal Districts (23)
('West Bengal', 'Alipurduar', 'AL'),
('West Bengal', 'Bankura', 'BN'),
('West Bengal', 'Birbhum', 'BI'),
('West Bengal', 'Cooch Behar', 'CO'),
('West Bengal', 'Dakshin Dinajpur', 'DD'),
('West Bengal', 'Darjeeling', 'DA'),
('West Bengal', 'Hooghly', 'HO'),
('West Bengal', 'Howrah', 'HW'),
('West Bengal', 'Jalpaiguri', 'JA'),
('West Bengal', 'Jhargram', 'JH'),
('West Bengal', 'Kalimpong', 'KL'),
('West Bengal', 'Kolkata', 'KO'),
('West Bengal', 'Malda', 'MA'),
('West Bengal', 'Murshidabad', 'MU'),
('West Bengal', 'Nadia', 'NA'),
('West Bengal', 'North 24 Parganas', 'NP'),
('West Bengal', 'Paschim Bardhaman', 'PB'),
('West Bengal', 'Paschim Medinipur', 'PM'),
('West Bengal', 'Purba Bardhaman', 'PUB'),
('West Bengal', 'Purba Medinipur', 'PEM'),
('West Bengal', 'Purulia', 'PU'),
('West Bengal', 'South 24 Parganas', 'SP'),
('West Bengal', 'Uttar Dinajpur', 'UD'),
-- Kerala Districts (14)
('Kerala', 'Alappuzha', 'AL'),
('Kerala', 'Ernakulam', 'ER'),
('Kerala', 'Idukki', 'ID'),
('Kerala', 'Kannur', 'KN'),
('Kerala', 'Kasaragod', 'KS'),
('Kerala', 'Kollam', 'KL'),
('Kerala', 'Kottayam', 'KT'),
('Kerala', 'Kozhikode', 'KZ'),
('Kerala', 'Malappuram', 'ML'),
('Kerala', 'Palakkad', 'PL'),
('Kerala', 'Pathanamthitta', 'PT'),
('Kerala', 'Thiruvananthapuram', 'TV'),
('Kerala', 'Thrissur', 'TS'),
('Kerala', 'Wayanad', 'WY'),
-- Punjab Districts (23)
('Punjab', 'Amritsar', 'AM'),
('Punjab', 'Barnala', 'BA'),
('Punjab', 'Bathinda', 'BT'),
('Punjab', 'Faridkot', 'FA'),
('Punjab', 'Fatehgarh Sahib', 'FS'),
('Punjab', 'Fazilka', 'FZ'),
('Punjab', 'Ferozepur', 'FO'),
('Punjab', 'Gurdaspur', 'GU'),
('Punjab', 'Hoshiarpur', 'HO'),
('Punjab', 'Jalandhar', 'JA'),
('Punjab', 'Kapurthala', 'KA'),
('Punjab', 'Ludhiana', 'LU'),
('Punjab', 'Mansa', 'MA'),
('Punjab', 'Moga', 'MO'),
('Punjab', 'Mohali', 'SAS'),
('Punjab', 'Muktsar', 'MK'),
('Punjab', 'Nawanshahr', 'NW'),
('Punjab', 'Pathankot', 'PT'),
('Punjab', 'Patiala', 'PA'),
('Punjab', 'Rupnagar', 'RU'),
('Punjab', 'Sangrur', 'SA'),
('Punjab', 'Tarn Taran', 'TT'),
-- Haryana Districts (22)
('Haryana', 'Ambala', 'AM'),
('Haryana', 'Bhiwani', 'BH'),
('Haryana', 'Charkhi Dadri', 'CD'),
('Haryana', 'Faridabad', 'FA'),
('Haryana', 'Fatehabad', 'FT'),
('Haryana', 'Gurugram', 'GU'),
('Haryana', 'Hisar', 'HI'),
('Haryana', 'Jhajjar', 'JJ'),
('Haryana', 'Jind', 'JN'),
('Haryana', 'Kaithal', 'KA'),
('Haryana', 'Karnal', 'KR'),
('Haryana', 'Kurukshetra', 'KU'),
('Haryana', 'Mahendragarh', 'MA'),
('Haryana', 'Nuh', 'NU'),
('Haryana', 'Palwal', 'PA'),
('Haryana', 'Panchkula', 'PC'),
('Haryana', 'Panipat', 'PN'),
('Haryana', 'Rewari', 'RE'),
('Haryana', 'Rohtak', 'RO'),
('Haryana', 'Sirsa', 'SI'),
('Haryana', 'Sonipat', 'SO'),
('Haryana', 'Yamunanagar', 'YA'),
-- Bihar Districts (38)
('Bihar', 'Araria', 'AR'),
('Bihar', 'Arwal', 'AW'),
('Bihar', 'Aurangabad', 'AU'),
('Bihar', 'Banka', 'BA'),
('Bihar', 'Begusarai', 'BG'),
('Bihar', 'Bhagalpur', 'BH'),
('Bihar', 'Bhojpur', 'BJ'),
('Bihar', 'Buxar', 'BX'),
('Bihar', 'Darbhanga', 'DA'),
('Bihar', 'East Champaran', 'EC'),
('Bihar', 'Gaya', 'GA'),
('Bihar', 'Gopalganj', 'GO'),
('Bihar', 'Jamui', 'JA'),
('Bihar', 'Jehanabad', 'JH'),
('Bihar', 'Kaimur', 'KI'),
('Bihar', 'Katihar', 'KT'),
('Bihar', 'Khagaria', 'KH'),
('Bihar', 'Kishanganj', 'KS'),
('Bihar', 'Lakhisarai', 'LA'),
('Bihar', 'Madhepura', 'MD'),
('Bihar', 'Madhubani', 'MB'),
('Bihar', 'Munger', 'MU'),
('Bihar', 'Muzaffarpur', 'MZ'),
('Bihar', 'Nalanda', 'NA'),
('Bihar', 'Nawada', 'NW'),
('Bihar', 'Patna', 'PA'),
('Bihar', 'Purnia', 'PU'),
('Bihar', 'Rohtas', 'RO'),
('Bihar', 'Saharsa', 'SA'),
('Bihar', 'Samastipur', 'SM'),
('Bihar', 'Saran', 'SR'),
('Bihar', 'Sheikhpura', 'SH'),
('Bihar', 'Sheohar', 'SE'),
('Bihar', 'Sitamarhi', 'SI'),
('Bihar', 'Siwan', 'SW'),
('Bihar', 'Supaul', 'SU'),
('Bihar', 'Vaishali', 'VA'),
('Bihar', 'West Champaran', 'WC'),
-- Odisha Districts (30)
('Odisha', 'Angul', 'AN'),
('Odisha', 'Balangir', 'BL'),
('Odisha', 'Balasore', 'BA'),
('Odisha', 'Bargarh', 'BG'),
('Odisha', 'Bhadrak', 'BH'),
('Odisha', 'Boudh', 'BO'),
('Odisha', 'Cuttack', 'CU'),
('Odisha', 'Debagarh', 'DE'),
('Odisha', 'Dhenkanal', 'DH'),
('Odisha', 'Gajapati', 'GA'),
('Odisha', 'Ganjam', 'GJ'),
('Odisha', 'Jagatsinghapur', 'JA'),
('Odisha', 'Jajpur', 'JJ'),
('Odisha', 'Jharsuguda', 'JH'),
('Odisha', 'Kalahandi', 'KL'),
('Odisha', 'Kandhamal', 'KN'),
('Odisha', 'Kendrapara', 'KE'),
('Odisha', 'Kendujhar', 'KJ'),
('Odisha', 'Khordha', 'KH'),
('Odisha', 'Koraput', 'KO'),
('Odisha', 'Malkangiri', 'ML'),
('Odisha', 'Mayurbhanj', 'MY'),
('Odisha', 'Nabarangpur', 'NB'),
('Odisha', 'Nayagarh', 'NA'),
('Odisha', 'Nuapada', 'NU'),
('Odisha', 'Puri', 'PU'),
('Odisha', 'Rayagada', 'RA'),
('Odisha', 'Sambalpur', 'SA'),
('Odisha', 'Subarnapur', 'SU'),
('Odisha', 'Sundargarh', 'SD'),
-- Assam Districts (35)
('Assam', 'Baksa', 'BA'),
('Assam', 'Barpeta', 'BT'),
('Assam', 'Biswanath', 'BI'),
('Assam', 'Bongaigaon', 'BG'),
('Assam', 'Cachar', 'CA'),
('Assam', 'Charaideo', 'CH'),
('Assam', 'Chirang', 'CI'),
('Assam', 'Darrang', 'DA'),
('Assam', 'Dhemaji', 'DH'),
('Assam', 'Dhubri', 'DB'),
('Assam', 'Dibrugarh', 'DI'),
('Assam', 'Dima Hasao', 'DM'),
('Assam', 'Goalpara', 'GO'),
('Assam', 'Golaghat', 'GL'),
('Assam', 'Hailakandi', 'HA'),
('Assam', 'Hojai', 'HO'),
('Assam', 'Jorhat', 'JO'),
('Assam', 'Kamrup', 'KM'),
('Assam', 'Kamrup Metropolitan', 'KMM'),
('Assam', 'Karbi Anglong', 'KA'),
('Assam', 'Karimganj', 'KG'),
('Assam', 'Kokrajhar', 'KO'),
('Assam', 'Lakhimpur', 'LA'),
('Assam', 'Majuli', 'MJ'),
('Assam', 'Morigaon', 'MO'),
('Assam', 'Nagaon', 'NA'),
('Assam', 'Nalbari', 'NL'),
('Assam', 'Sivasagar', 'SI'),
('Assam', 'Sonitpur', 'SO'),
('Assam', 'South Salmara Mankachar', 'SS'),
('Assam', 'Tinsukia', 'TI'),
('Assam', 'Udalguri', 'UD'),
('Assam', 'West Karbi Anglong', 'WK'),
-- Jharkhand Districts (24)
('Jharkhand', 'Bokaro', 'BK'),
('Jharkhand', 'Chatra', 'CH'),
('Jharkhand', 'Deoghar', 'DE'),
('Jharkhand', 'Dhanbad', 'DH'),
('Jharkhand', 'Dumka', 'DU'),
('Jharkhand', 'East Singhbhum', 'ES'),
('Jharkhand', 'Garhwa', 'GA'),
('Jharkhand', 'Giridih', 'GI'),
('Jharkhand', 'Godda', 'GO'),
('Jharkhand', 'Gumla', 'GU'),
('Jharkhand', 'Hazaribag', 'HA'),
('Jharkhand', 'Jamtara', 'JA'),
('Jharkhand', 'Khunti', 'KH'),
('Jharkhand', 'Koderma', 'KO'),
('Jharkhand', 'Latehar', 'LA'),
('Jharkhand', 'Lohardaga', 'LO'),
('Jharkhand', 'Pakur', 'PA'),
('Jharkhand', 'Palamu', 'PL'),
('Jharkhand', 'Ramgarh', 'RA'),
('Jharkhand', 'Ranchi', 'RU'),
('Jharkhand', 'Sahebganj', 'SA'),
('Jharkhand', 'Seraikela Kharsawan', 'SK'),
('Jharkhand', 'Simdega', 'SI'),
('Jharkhand', 'West Singhbhum', 'WS')
) AS d(state, name, code)
WHERE s.name = d.state
ON CONFLICT DO NOTHING;
