/*
# India Districts - Part 1

Inserting districts for major states.
*/

INSERT INTO districts (state_id, name, code)
SELECT s.id, d.name, d.code FROM states s, (VALUES
-- Telangana Districts (33) 
('Telangana', 'Adilabad', 'AD'),
('Telangana', 'Bhadradri Kothagudem', 'BK'),
('Telangana', 'Hyderabad', 'HY'),
('Telangana', 'Jagtial', 'JG'),
('Telangana', 'Jangaon', 'JA'),
('Telangana', 'Jayashankar Bhupalpally', 'JB'),
('Telangana', 'Jogulamba Gadwal', 'JGG'),
('Telangana', 'Kamareddy', 'KM'),
('Telangana', 'Karimnagar', 'KR'),
('Telangana', 'Khammam', 'KH'),
('Telangana', 'Komaram Bheem Asifabad', 'KA'),
('Telangana', 'Mahabubabad', 'MB'),
('Telangana', 'Mahabubnagar', 'MH'),
('Telangana', 'Mancherial', 'MC'),
('Telangana', 'Medak', 'MD'),
('Telangana', 'Medchal Malkajgiri', 'MM'),
('Telangana', 'Mulugu', 'ML'),
('Telangana', 'Nagarkurnool', 'NK'),
('Telangana', 'Nalgonda', 'NL'),
('Telangana', 'Narayanpet', 'NP'),
('Telangana', 'Nirmal', 'NML'),
('Telangana', 'Nizamabad', 'NZ'),
('Telangana', 'Peddapalli', 'PD'),
('Telangana', 'Rajanna Sircilla', 'RS'),
('Telangana', 'Rangareddy', 'RR'),
('Telangana', 'Sangareddy', 'SA'),
('Telangana', 'Siddipet', 'SI'),
('Telangana', 'Suryapet', 'SR'),
('Telangana', 'Vikarabad', 'VB'),
('Telangana', 'Wanaparthy', 'WP'),
('Telangana', 'Warangal Rural', 'WR'),
('Telangana', 'Warangal Urban', 'WU'),
('Telangana', 'Yadadri Bhuvanagiri', 'YB'),
-- Andhra Pradesh Districts (26)
('Andhra Pradesh', 'Alluri Sitharama Raju', 'ASR'),
('Andhra Pradesh', 'Anakapalli', 'AK'),
('Andhra Pradesh', 'Anantapur', 'AT'),
('Andhra Pradesh', 'Annamayya', 'AY'),
('Andhra Pradesh', 'Bapatla', 'BT'),
('Andhra Pradesh', 'Chittoor', 'CT'),
('Andhra Pradesh', 'East Godavari', 'EG'),
('Andhra Pradesh', 'Eluru', 'EL'),
('Andhra Pradesh', 'Guntur', 'GT'),
('Andhra Pradesh', 'Kakinada', 'KI'),
('Andhra Pradesh', 'Konaseema', 'KS'),
('Andhra Pradesh', 'Krishna', 'KS'),
('Andhra Pradesh', 'Kurnool', 'KL'),
('Andhra Pradesh', 'Nandyal', 'NY'),
('Andhra Pradesh', 'NTR', 'NTR'),
('Andhra Pradesh', 'Palnadu', 'PN'),
('Andhra Pradesh', 'Parvathipuram Manyam', 'PM'),
('Andhra Pradesh', 'Prakasam', 'PR'),
('Andhra Pradesh', 'Sri Potti Sriramulu Nellore', 'SPS'),
('Andhra Pradesh', 'Srikakulam', 'SK'),
('Andhra Pradesh', 'Tirupati', 'TP'),
('Andhra Pradesh', 'Visakhapatnam', 'VS'),
('Andhra Pradesh', 'Vizianagaram', 'VZ'),
('Andhra Pradesh', 'West Godavari', 'WG'),
('Andhra Pradesh', 'YSR Kadapa', 'YSR'),
-- Karnataka Districts (31)
('Karnataka', 'Bagalkot', 'BK'),
('Karnataka', 'Bangalore Rural', 'BR'),
('Karnataka', 'Bangalore Urban', 'BU'),
('Karnataka', 'Belgaum', 'BG'),
('Karnataka', 'Bellary', 'BL'),
('Karnataka', 'Bidar', 'BD'),
('Karnataka', 'Bijapur', 'BJ'),
('Karnataka', 'Chamarajanagar', 'CM'),
('Karnataka', 'Chikballapur', 'CK'),
('Karnataka', 'Chikkamagaluru', 'CB'),
('Karnataka', 'Chitradurga', 'CD'),
('Karnataka', 'Dakshina Kannada', 'DK'),
('Karnataka', 'Davanagere', 'DV'),
('Karnataka', 'Dharwad', 'DH'),
('Karnataka', 'Gadag', 'GD'),
('Karnataka', 'Gulbarga', 'GB'),
('Karnataka', 'Hassan', 'HS'),
('Karnataka', 'Haveri', 'HV'),
('Karnataka', 'Kodagu', 'KG'),
('Karnataka', 'Kolar', 'KR'),
('Karnataka', 'Koppal', 'KP'),
('Karnataka', 'Mandya', 'MY'),
('Karnataka', 'Mysore', 'MS'),
('Karnataka', 'Raichur', 'RC'),
('Karnataka', 'Ramanagara', 'RM'),
('Karnataka', 'Shimoga', 'SH'),
('Karnataka', 'Tumkur', 'TM'),
('Karnataka', 'Udupi', 'UD'),
('Karnataka', 'Uttara Kannada', 'UK'),
('Karnataka', 'Vijayapura', 'VP'),
('Karnataka', 'Yadgir', 'YG'),
-- Maharashtra Districts (36)
('Maharashtra', 'Ahmednagar', 'AH'),
('Maharashtra', 'Akola', 'AK'),
('Maharashtra', 'Amravati', 'AM'),
('Maharashtra', 'Beed', 'BD'),
('Maharashtra', 'Bhandara', 'BH'),
('Maharashtra', 'Buldhana', 'BL'),
('Maharashtra', 'Chandrapur', 'CH'),
('Maharashtra', 'Dhule', 'DH'),
('Maharashtra', 'Gadchiroli', 'GD'),
('Maharashtra', 'Gondia', 'GO'),
('Maharashtra', 'Hingoli', 'HI'),
('Maharashtra', 'Jalgaon', 'JL'),
('Maharashtra', 'Jalna', 'JA'),
('Maharashtra', 'Kolhapur', 'KL'),
('Maharashtra', 'Latur', 'LA'),
('Maharashtra', 'Mumbai City', 'MC'),
('Maharashtra', 'Mumbai Suburban', 'MS'),
('Maharashtra', 'Nagpur', 'NG'),
('Maharashtra', 'Nanded', 'NA'),
('Maharashtra', 'Nandurbar', 'NB'),
('Maharashtra', 'Nashik', 'NK'),
('Maharashtra', 'Osmanabad', 'OS'),
('Maharashtra', 'Palghar', 'PL'),
('Maharashtra', 'Parbhani', 'PB'),
('Maharashtra', 'Pune', 'PN'),
('Maharashtra', 'Raigad', 'RG'),
('Maharashtra', 'Ratnagiri', 'RT'),
('Maharashtra', 'Sangli', 'SG'),
('Maharashtra', 'Satara', 'ST'),
('Maharashtra', 'Sindhudurg', 'SI'),
('Maharashtra', 'Solapur', 'SO'),
('Maharashtra', 'Thane', 'TH'),
('Maharashtra', 'Wardha', 'WR'),
('Maharashtra', 'Washim', 'WA'),
('Maharashtra', 'Yavatmal', 'YA'),
-- Tamil Nadu Districts (38)
('Tamil Nadu', 'Ariyalur', 'AR'),
('Tamil Nadu', 'Chengalpattu', 'CG'),
('Tamil Nadu', 'Chennai', 'CH'),
('Tamil Nadu', 'Coimbatore', 'CO'),
('Tamil Nadu', 'Cuddalore', 'CU'),
('Tamil Nadu', 'Dharmapuri', 'DH'),
('Tamil Nadu', 'Dindigul', 'DI'),
('Tamil Nadu', 'Erode', 'ER'),
('Tamil Nadu', 'Kallakurichi', 'KK'),
('Tamil Nadu', 'Kanchipuram', 'KA'),
('Tamil Nadu', 'Kanyakumari', 'KN'),
('Tamil Nadu', 'Karur', 'KR'),
('Tamil Nadu', 'Krishnagiri', 'KS'),
('Tamil Nadu', 'Madurai', 'MY'),
('Tamil Nadu', 'Mayiladuthurai', 'ML'),
('Tamil Nadu', 'Nagapattinam', 'NG'),
('Tamil Nadu', 'Namakkal', 'NM'),
('Tamil Nadu', 'Nilgiris', 'NI'),
('Tamil Nadu', 'Perambalur', 'PE'),
('Tamil Nadu', 'Pudukkottai', 'PU'),
('Tamil Nadu', 'Ramanathapuram', 'RM'),
('Tamil Nadu', 'Ranipet', 'RP'),
('Tamil Nadu', 'Salem', 'SA'),
('Tamil Nadu', 'Sivaganga', 'SI'),
('Tamil Nadu', 'Tenkasi', 'TE'),
('Tamil Nadu', 'Thanjavur', 'TH'),
('Tamil Nadu', 'Theni', 'TN'),
('Tamil Nadu', 'Thoothukudi', 'TT'),
('Tamil Nadu', 'Tiruchirappalli', 'TR'),
('Tamil Nadu', 'Tirunelveli', 'TI'),
('Tamil Nadu', 'Tirupathur', 'TP'),
('Tamil Nadu', 'Tiruppur', 'TJ'),
('Tamil Nadu', 'Tiruvannamalai', 'TV'),
('Tamil Nadu', 'Tiruvarur', 'TU'),
('Tamil Nadu', 'Vellore', 'VL'),
('Tamil Nadu', 'Viluppuram', 'VI'),
('Tamil Nadu', 'Virudhunagar', 'VR')
) AS d(state, name, code)
WHERE s.name = d.state
ON CONFLICT DO NOTHING;
